### ISSUE TITLE
Assertion output is hard to read in non-terminal outputs

### ISSUE THREAD

**Issue by sazzer** [MarvinJWendt/testza#12]
I've just recently discovered this library and am finding it great. However, one issue I've got is that the output is really hard to read in VSCode instead of in a terminal.

In VSCode it looks like this:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/66072/129625257-c38bcba6-171c-4b55-b086-a5abc41d5917.png">

And the exact same in the terminal looks like this:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/66072/129625325-0403aadf-958d-4e8b-98fc-a205ccffb007.png">

Cheers

**Comment by MarvinJWendt** [comment]
Hi @sazzer. This is actually very weird behavior. Testza uses [PTerm](https://github.com/pterm/pterm) for coloring output, and VS Code is actively tested to work with PTerm.

In my VS Code it works just fine:

![image](https://user-images.githubusercontent.com/31022056/129648698-b2fe5847-653f-48ef-ae85-2fba453263a9.png)

Looks like your VSC **somehow** doesn't interpret ANSI codes (for whatever reason).
If I start a clean build of VSC (every setting to default, and no extensions) the terminal also works fine with testza.

Since I am also the author of [PTerm](https://github.com/pterm/pterm), I can say that we never had any issues with VSC and ANSI codes.

I am also curious, why some stuff gets colored in your terminal, like (len=9):
![image](https://user-images.githubusercontent.com/31022056/129649082-e0e37e60-4a24-4320-b608-732460f90e28.png)

Do you have any extensions, that color terminal output, installed in VSC? They might be interfering with our color codes.

Could you please try to start VSC without extensions, and tell me if that solves your problem?

```
Developer: Reload With Extensions Disabled
```

![image](https://user-images.githubusercontent.com/31022056/129649663-2274ec99-7af2-42e2-bc04-e7316ab7a7f3.png)

**Comment by sazzer** [comment]
That's actually a good point. Thank you.

It's not VSCode specifically. It's the "Test Explorer" extension that I'm using to run the tests with.

I'm not sure if the real issue is that "Test Explorer" doesn't support colour output, or that "Testza" doesn't detect that the output target doesn't support colour and then turn it off.

**Comment by MarvinJWendt** [comment]
Well, the thing is that the output target stays the same (your shell [eg. Bash, PowerShell, etc.]), what your VSC extensions do with the output, can not be accessed by testza, as that happens after the output is already printed, but before it's displayed in the terminal. 

"Test Explorer" colors the output with pattern matching, and the problem is that it detects some of testzas output, as output that should be colored.

I can give you a quick example on how ANSI codes work:  
(the codes are made up to make them more readable)

```
# This gets printed to your terminal
[COLOR=RED]Some red text[COLOR=GREEN] Some green text
```

Now Test Explorer detects a pattern inside our codes and messes things up like this:

```
[COLOR=RED[COLOR=GREEN]]Some text that should be red
```

Now the codes are no longer valid and get written to the terminal, as it can no longer interpret the ANSI codes as commands. This is why you get that text:
![image](https://user-images.githubusercontent.com/31022056/129818882-7633c6b5-3cbc-4068-93d9-8f8006b0310a.png)
(These are some (broken) ANSI codes)

We'll introduce a feature to disable colored output manually, but there is no way to detect what happens after we print the text to the terminal. All modifications that appear after the call to your terminal are inaccessible.

Also the issue, that VSC cannot display colors in the "Output" tab, is known and discussed here: https://github.com/microsoft/vscode-go/issues/2003

And here: https://github.com/golang/vscode-go/issues/187

This issue also suggests, that the output is (falsely) detected as log output: https://github.com/microsoft/vscode/issues/43271

If you have any future questions, regarding this, or anything else, make sure to hit me up 😄
